### ISSUE TITLE
Actually send it, not just a private sender

### ISSUE THREAD

**Issue by ShadiestGoat** [luimu64/stallman-powercord#1]
Rather than doing `p!stallman {word}`, then copying it an pasting it, please make it so that it auto sends it. Its a simple fix:

```js
return {
                    send: true, //you can also use the send variable, or add it to settings or something
                    result: copypasta
                };
```

**Comment by luimu64** [comment]
you can just use the -s flag. I can however make it work the otherway around so it sends it as message by default and using flag makes it post it with the bot.

**Comment by luimu64** [comment]
I changed the default behavior from needing to use the -s to sending it directly and -bot flag being optional. https://github.com/luimu64/stallman-powercord/commit/cef5d64dc044427a4c1bd985006c63e92a296eaf
